apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      containers:
        - name: devops-challenge-container
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}

          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}