apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.Name }}
spec:
  rules:
    - http:
        paths:
          - path: /my-app
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.Name }}
                port:
                  number: {{ .Values.service.port }}
