apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}
spec:
  selector:
    app: {{ .Values.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP